version: "3"
services:
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./html/:/var/www/html/"
    ports:
      - "8080:80"
  mysql-server:
    image: mysql:8.0.19
    restart: always
    env_file: env_file/mysql.env
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    env_file: env_file/pma.env
    environment:
      PMA_HOST: "${PMA_HOST}"
      PMA_USER: "${PMA_USER}"
      PMA_PASSWORD: "${PMA_PASSWORD}"
    ports:
      - "5000:80"

  reverseproxy:
    image: nginx
    container_name: nginx-docker
    volumes:
       - "./etc/nginx/conf.d:/etc/nginx/conf.d"
       - "./etc/ssl:/etc/ssl"
       - "./html:/var/www/html"
       - "./etc/nginx/conf.d/default.template:/etc/nginx/conf.d/default.template"
       - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
       - "./etc/nginx/log/error.log:/var/log/nginx/error.log"
    ports:
       - "80:80"
       - "443:443"
    environment:
       - NGINX_HOST=${NGINX_HOST}
    command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
       - mysql-server
       - web-server

volumes:
  mysql-data:
